print('請輸入個人基本資料')
name = input('姓名： ')
age = input('年齡： ')
phone = input('電話： ')
adress = input('住址： ')
sos_name = input('緊急聯絡人姓名： ')
sos_phone = input('緊急聯絡人電話： ')
print('您的姓名： ', name)
print('您的年齡： ', age)
print('您的電話： ', phone)
print('您的住址： ', adress)
print('您的緊急聯絡人姓名： ', sos_name)
print('您的緊急聯絡人電話： ', sos_phone)
print('Hi', name,'你', age, '歲', '你的電話號碼: ', phone)
num = input('請輸入任一數字： ')
print('恭喜你！在這個空無一物的世界裡，創造了一個名為',num ,'的物品。')	